basic_settings:
  site_title: Apricot
  site_tagline:
  favicon_image: '/images/favicon.png'
  touch_icon_image: '/images/touch.png'

header_settings:
  logo_image: '/images/logo.png'
  logo_width: 300

menu_settings:
  menu_items:
    - title: 'Game'
      url: '/game'
    - title: 'Anime'
      url: '/anime'
    - title: 'Others'
      url: '/others'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  overlay_opacity: 0.7
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  weibo_url: 'sfs'
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#0C5DF2'
  border_color: '#dddddd'
  overlay_background_color: '#0C5DF2'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: ''
  title_font: '"Helvetica Neue",Helvetica,Arial,"Microsoft Yahei","Hiragino Sans GB","Heiti SC","WenQuanYi Micro Hei",sans-serif;'
  body_font: '"Helvetica Neue",Helvetica,Arial,"Microsoft Yahei","Hiragino Sans GB","Heiti SC","WenQuanYi Micro Hei",sans-serif;'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 16
    medium_size: 20
    large_size: 24
    weight: 200
    letter_spacing: 0.1
    line_height: 1.6
  grid_item_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
